### ISSUE TITLE
Cant load roms on 4.0.1?

### ISSUE THREAD

**Issue by gideongek** [masterfeizz/DeSmuME-NX#5]
I have done what you have said and it just wont load or something
![20180521_154419](https://user-images.githubusercontent.com/16256978/40310697-f2ffe8ca-5d0d-11e8-8666-120cd1bc991a.jpg)

Idk if this is a bug or just a fault on my end. I do have roms in the rom folder.

**Comment by masterfeizz** [comment]
I've only encountered that bug once, it was due to a failed file transfer. Try copying the rom again or maybe try a different one.

**Comment by gideongek** [comment]
Many thanks. Idk what it was but it it now fixed

**Comment by gotwig** [comment]
Then you should close the ticket :D ^^
