### ISSUE TITLE
Last commit over 1 month ago, is this project dead?

### ISSUE THREAD

**Issue by Favna** [masterfeizz/DeSmuME-NX#8]
For an open source project one would expect to either see a notice that the development is very slow or gradually incoming commits. Are you still working on this project at all?

**Comment by Laproxi** [comment]
I would also like to know: I created a mod for this port that greatly benefits users, but is pointless without future support and optimised emulation.

**Comment by masterfeizz** [comment]
No, I'm not working on this anymore.

**Comment by Favna** [comment]
Okay so you could you at least take less than a minute out of your day to update your readme and say it is abandoned? That is common courtesy for GitHub open source projects. 

IF you want to go one step further you could also archvie the repo in the repo settings.
